version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Updating system packages"
      - yum update -y

      - echo "Installing basic tools"
      - yum install -y git tree unzip curl wget

      - echo "Installing AWS CLI v2"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install

      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/

  build:
    commands:
      - echo "Changing to Terraform directory"
      - cd Terraform-iac-code

      - echo "Terraform init"
      - terraform init

      - echo "Terraform plan"
      - terraform plan

      - echo "Terraform apply"
      - terraform apply -auto-approve
